install.packages("babynames")
install.packages("tidyverse")
library("tidyverse")
library("babynames")
library("tibble")
library("dplyr")
select(babynames, name)
select(babynames, name, year)
select(babynames, year, sex, name, n)
filter(babynames, name == "Khaleesi")
